name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install react-icons

      - name: Run tests
        run: npm test
